// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_riverpod_stream_todo_app/test/utils/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:flutter_riverpod_stream_todo_app/data/dto/todo_dto.dart' as _i7;
import 'package:flutter_riverpod_stream_todo_app/data/repository/todo_repository.dart'
    as _i6;
import 'package:flutter_riverpod_stream_todo_app/domain/logic/async_todo_notifier.dart'
    as _i3;
import 'package:flutter_riverpod_stream_todo_app/domain/model/todo.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAsyncNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.AsyncNotifierProviderRef<T> {
  _FakeAsyncNotifierProviderRef_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAsyncValue_1<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRef_2<State extends Object?> extends _i1.SmartFake
    implements _i2.Ref<State> {
  _FakeRef_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoNotifier extends _i1.Mock implements _i3.TodoNotifier {
  MockTodoNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AsyncNotifierProviderRef<List<_i4.Todo>> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeAsyncNotifierProviderRef_0<List<_i4.Todo>>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.AsyncNotifierProviderRef<List<_i4.Todo>>);

  @override
  _i2.AsyncValue<List<_i4.Todo>> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAsyncValue_1<List<_i4.Todo>>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.AsyncValue<List<_i4.Todo>>);

  @override
  _i5.Future<List<_i4.Todo>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i5.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i5.Future<List<_i4.Todo>>);

  @override
  set state(_i2.AsyncValue<List<_i4.Todo>>? newState) => super.noSuchMethod(
    Invocation.setter(#state, newState),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i4.Todo>> build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _i5.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i5.Future<List<_i4.Todo>>);

  @override
  _i5.Future<void> addTodo(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#addTodo, [title]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void listenSelf(
    void Function(
      _i2.AsyncValue<List<_i4.Todo>>?,
      _i2.AsyncValue<List<_i4.Todo>>,
    )?
    listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i4.Todo>> update(
    _i5.FutureOr<List<_i4.Todo>> Function(List<_i4.Todo>)? cb, {
    _i5.FutureOr<List<_i4.Todo>> Function(Object, StackTrace)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [cb], {#onError: onError}),
            returnValue: _i5.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i5.Future<List<_i4.Todo>>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<List<_i4.Todo>>? previous,
    _i2.AsyncValue<List<_i4.Todo>>? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i6.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ref<Object?> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeRef_2<Object?>(this, Invocation.getter(#ref)),
          )
          as _i2.Ref<Object?>);

  @override
  _i5.Stream<List<_i7.TodoDto>> fetchTodos() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTodos, []),
            returnValue: _i5.Stream<List<_i7.TodoDto>>.empty(),
          )
          as _i5.Stream<List<_i7.TodoDto>>);

  @override
  _i5.Future<void> addTodo(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#addTodo, [title]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
